development:
  GMAIL_ADDRESS:
  GMAIL_APP_PASSWORD:
  DEFAULT_MAIL_FROM_ADDRESS:
  DEFAULT_MAIL_TO_ADDRESS:
  CLOUDINARY_CLOUD_NAME:
  CLOUDINARY_API_KEY:
  CLOUDINARY_API_SECRET:

production:
  GMAIL_ADDRESS:
  GMAIL_APP_PASSWORD:
  DEFAULT_MAIL_FROM_ADDRESS:
  DEFAULT_MAIL_TO_ADDRESS:
  CLOUDINARY_CLOUD_NAME:
  CLOUDINARY_API_KEY:
  CLOUDINARY_API_SECRET:
