development:
  GMAIL_ADDRESS:
  GMAIL_APP_PASSWORD: 
  MAILER_HOST: localhost
  MAILER_PORT: 3000
  DEFAULT_MAIL_FROM_ADDRESS: 
  DEFAULT_MAIL_TO_ADDRESS:

production:
  GMAIL_ADDRESS:
  GMAIL_APP_PASSWORD:
  MAILER_HOST:
  MAILER_PORT:
  DEFAULT_MAIL_FROM_ADDRESS: 
  DEFAULT_MAIL_TO_ADDRESS:
